### ISSUE TITLE
JS flist should work out of the box

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/home#14]
Should include jsenv
should source jsenv from within jumpscale

**Comment by arahmanhamdy** [comment]
https://github.com/Jumpscale/home/commit/1e9ff31f9f1d5f63c662896056fef62735520e50

**Comment by Dinaamagdy** [comment]
Doesn't work in 0-core version 93dfafae4e1fc7ec06c92b6b4de4e16a06edc112 as env doesn't pass correctly

**Comment by islamTaha12** [comment]
Can't validate till this issue https://github.com/zero-os/0-hub/issues/27 be fixed

**Comment by Dinaamagdy** [comment]
validated
