### ISSUE TITLE
Story: configmanager integration in js93

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/home#21]
- need to make sure that all SAL Clients use the new configmanager functionality

**Comment by rkhamis** [comment]
clients:

[ ] agentcontroller
[ ] atyourservice
[ ] ays
[ ] celery
[ ] dns
[ ] domainmanager
[ ] email
[ ] etcd
[ ] g8core
[ ] git
[ ] gitea
[ ] github
[ ] gitlab
[ ] gogs
[ ] google_compute
[ ] grafana
[ ] graphite
[ ] http
[ ] influxdb
[ ] itsyouonline
[ ] kubernetes
[ ] mongodb
[ ] mysql
[ ] oauth
[ ] openvcloud
[ ] osticket
[ ] ovh
[ ] packetnet
[ ] peewee
[ ] portal
[ ] postgres
[ ] racktivity
[ ] redis
[ ] rogerthat
[ ] sendgrid
[ ] skydns
[ ] sqlalchemy
[ ] ssh
[ ] storx
[ ] syncthing
[ ] tarantool
[ ] whmcs
[ ] zero_os
[ ] zerohub
[ ] zerostor
[ ] zerotier
[ ] zrobot
