### ISSUE TITLE
migration from 9.2.1 to 9.3.0

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/home#23]
incomplete spec:

Should migrate:
 - [ ] g8client service to secure configuration-enabled service
 - [ ] blueprints to new blueprints with cfgmgr
 - [ ] `cockpit_repos` to `ays_repos`

**Comment by arahmanhamdy** [comment]
working on  `g8client service to secure configuration-enabled service`

**Comment by arahmanhamdy** [comment]
https://github.com/openvcloud/ays_templates/commit/4519e03916a99d3d95387e1a1cc3f444ac6ec283
https://github.com/Jumpscale/ays9/commit/eda5ba9ea036b031a507fcfff3c0e044ee93179f
