### ISSUE TITLE
dns & core models behind gedis

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/home#27]
- gedis & models to allow management of following objects

- user/group
- name services
- farmingpools/farmers

requirements

- redundant data
- easy to use in python
- documented how to use
- capnp serialization
- usable from browser through redis proxy/json

**Comment by rkhamis** [comment]
SAL to abstract main models (capnp models):

- farmer:
  - farmer id
  - domain
  - group

- farmingpool:
  - list of farmers

- user:
   - itsyouonline id

- group:
   - itsyouonline group id

- nameservers:
   - to integrate with registering new subdomain  for new farmers?


register commands in gedis to set/list/get these models

**Comment by despiegk** [comment]
I will be doing this, I will need some help but not now
