### ISSUE TITLE
reality capturing & processing tool

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/home#3]
- use agent & agentcontroller8
- create a launch tool which schedules jobs to
  - read disk stats
  - read process stats (create a process reality object for all processes with same name, DO NOT work with pids !, id= name of process)
  - read vm stats
  - read docker stats
  - read nic stats
  - read reality info: disks, nics, vms, dockers, cpu, .... 
  - read / clean logs e.g. syslog, dmesg send to log
  - remark: at least everything we do in openvcloud + more should be done
- do this by creating a tool j.tools.realitycapture....
  - this does the reading of all info, use the models, send to redis
- use models as defined in: https://github.com/Jumpscale/jumpscale_core8/tree/master/lib/JumpScale/data/models
  - expand the models where required
- create a tool j.tools.realityprocess
  - this reads from the redis
  - stats to influxdb
  - logs to tar files for reference
  - eco & reality objects to mongodb

**Comment by despiegk** [comment]
create the scaleton first (classes with empty methods & documentation), let @despiegk review

**Comment by despiegk** [comment]
also need to make sure that the pages from the portal (grid portal space) shows all this info

**Comment by muhamadazmy** [comment]
I just created the skeleton for the realitycapture extension here.

https://github.com/Jumpscale/jumpscale_core8/blob/master/lib/JumpScale/tools/realitycapture/RealityCapture.py

The extension is just a factory to the Monitor class which only allows the caller to schedule monitoring tasks on remote node (over the agentcontroller8 and the agent8).

The scheduled jumpscript will then run according to the given crons, and then report stats (or reality objects) over the provided redis address.

could you please take a look?

**Comment by muhamadazmy** [comment]
@despiegk 
Also the `realitprocess` extension is implemented here  https://github.com/Jumpscale/jumpscale_core8/blob/master/lib/JumpScale/tools/aggregator/RealityProcess.py

It starts influxdumper and mongodumper, both logs and ecos dumpers are under development.

**Comment by despiegk** [comment]
skeleton should be much more

what are the methods to launch a monitoring task
how do you define on which nodes
which monitoring actions ...



On Sun, Feb 21, 2016 at 3:13 PM, Muhamad Azmy <notifications@github.com>
wrote:

> I just created the skeleton for the realitycapture extension here.
>
>
> https://github.com/Jumpscale/jumpscale_core8/blob/master/lib/JumpScale/tools/realitycapture/RealityCapture.py
>
> The extension is just a factory to the Monitor class which only allows the
> caller to schedule monitoring tasks on remote node (over the
> agentcontroller8 and the agent8).
>
> The scheduled jumpscript will then run according to the given crons, and
> then report stats (or reality objects) over the provided redis address.
>
> could you please take a look?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jumpscale/Home/issues/3#issuecomment-186828817>.
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk

**Comment by muhamadazmy** [comment]
@despiegk The reality process class only defines the factory, the methods to launch the monitoring tasks are defined here

https://github.com/Jumpscale/jumpscale_core8/blob/master/lib/JumpScale/tools/realitycapture/Monitor.py

As you can see, all methods accepts gid and nid combination which perfectly defines what nodes the monitor task should run on.

**Comment by despiegk** [comment]
how far are we with this story?

**Comment by muhamadazmy** [comment]
@despiegk 
- The realityprocess is done, all data from redis is processed and stored to reality databases (mongo and influxdb).
- The scripts we have already in jumpscale has been updated to use the aggregator extension to report statistics and reality objects.
- We will make sure that after https://github.com/0-complexity/home/issues/4 that all monitor jumpscripts will auto-schedule on the agents
- TODO: Build more jumpscripts to monitor VMs and Dockers (I personally think this should be part of OVC migration to JS8)

**Comment by despiegk** [comment]
OVC migration to JS8 is not planned soon
but we want already monitoring in js8 from controllers, its a step by step approach

**Comment by grimpy** [comment]
but we want already monitoring in js8 from controllers, its a step by step approach

What do you mean with this?
Monitor what from the controller exactly?
