### ISSUE TITLE
can we add 9.4.1 and 9.5.0 to milestones in jumpscale repo?

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/home#32]
can we add 9.4.1 and 9.5.0 to milestones in jumpscale repo?

**Comment by despiegk** [comment]
I see we use Roadmap here, is that intention, is it then everywhere Roadmap with R?

**Comment by rkhamis** [comment]
Created 9.4.1, 9.4.2, roadmap
I feel 9.5.0 is still too early to be defined yet
