### ISSUE TITLE
create documentation sites

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/home#33]
see how we did on https://github.com/rivine/recordchain/tree/master/docs

takes 10 min per site.

Enable the github pages under docs

fill in the _sidebar, can be multiple levels

for tips check

http://tools_wiki.threefold.me/

**Comment by despiegk** [comment]
do for:
- core
- lib
- prefab
- home
- zrobot
- ...

**Comment by PeterNashaat** [comment]
- it's done on these repos :- 
- core
- lib
- prefab
- home
- zrobot

- waiting pull request approve
- portal9
