### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/Home#4]
- on home page make sure we describe the repo's & their goals
- on home page put link to main sections in doc wiki books
    - install in 2 modes
    - ays

# linked issues
- jumpscale/docs8#1
- @todo please complete there is prob much more to fix in docs, lets list it all here and make sure issues exist on other docs8 repo

**Comment by despiegk** [comment]
@rkhamis check with team: 
- go over doc, remove outdated parts
- for playing with e.g. portal describe the j.cuisine.local.... way
- check the js8 install method

**Comment by grimpy** [comment]
Update to reflect cuisine changes
