### ISSUE TITLE
Daily Build Test

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/home#8]
Use our Jenkins [http://ci.codescalers.com/]() to daily test the cuisine "all" builder.
1. Bootstrap with agent (would be a good opportunity to verify https://github.com/Jumpscale/jumpscale_core8/pull/117
2. Use (and verify!) this script for testing: https://github.com/0-complexity/g8_lab_internal/pull/5
3. Add reports

**Comment by grimpy** [comment]
convert jumpscale/dockers to support standard dockerfiles.
Build the images in order
In build image build cuisine.all
Push into stor (bleeding edge flist?)
Build g8os

**Comment by grimpy** [comment]
@abdulrahmantkhalifa please add documentation before calling this done

**Comment by abdulrahmantkhalifa** [comment]
documentation -->  https://gig.gitbooks.io/jumpscale8/content/Jenkins/Jenkins_intro.html
